
package com.empresa.sistema.cointracker.util;

import java.util.ArrayList;
import java.util.List;


public class CountryList {
    public static List<String> countries(){
        List<String> countries = new ArrayList<String>();
        countries.add("Afeganistão");
        countries.add("África do Sul");
        countries.add("Albânia");
        countries.add("Alemanha");
        countries.add("Andorra");
        countries.add("Angola");
        countries.add("Antiga e Barbuda");
        countries.add("Arábia Saudita");
        countries.add("Argélia");
        countries.add("Argentina");
        countries.add("Arménia");
        countries.add("Austrália");
        countries.add("Áustria");
        countries.add("Azerbaijão");
        countries.add("Bahamas");
        countries.add("Bangladexe");
        countries.add("Barbados");
        countries.add("Barém");
        countries.add("Bélgica");
        countries.add("Belize");
        countries.add("BenimPorto ");
        countries.add("Bielorrússia");
        countries.add("Bolívia");
        countries.add("Bósnia e Herzegovina");
        countries.add("Botsuana");
        countries.add("Brasil");
        countries.add("Brunei");
        countries.add("Bulgária");
        countries.add("Burquina Faso");
        countries.add("Burúndi");
        countries.add("Butão");
        countries.add("Cabo Verde");
        countries.add("Camarões");
        countries.add("Camboja");
        countries.add("Canadá");
        countries.add("Catar");
        countries.add("Cazaquistão");
        countries.add("Chade");
        countries.add("Chile");
        countries.add("China");
        countries.add("Chipre");
        countries.add("Colômbia");
        countries.add("Comores");
        countries.add("Congo-Brazzaville");
        countries.add("Coreia do Norte");
        countries.add("Coreia do Sul");
        countries.add("Cosovo");
        countries.add("Costa do Marfim");
        countries.add("Costa Rica");
        countries.add("Croácia");
        countries.add("Cuaite");
        countries.add("Cuba");
        countries.add("Dinamarca");
        countries.add("Dominica");
        countries.add("Egito");
        countries.add("Emirados Árabes Unidos");
        countries.add("Equador");
        countries.add("Eritreia");
        countries.add("Eslováquia");
        countries.add("Eslovénia");
        countries.add("Espanha");
        countries.add("Estado da Palestina");
        countries.add("Estados Unidos");
        countries.add("Estónia");
        countries.add("EtiópiaAdis ");
        countries.add("Fiji");
        countries.add("Filipinas");
        countries.add("Finlândia");
        countries.add("França");
        countries.add("Gabão");
        countries.add("Gâmbia");
        countries.add("Gana");
        countries.add("Geórgia");
        countries.add("GranadaSão ");
        countries.add("Grécia");
        countries.add("Guatemala");
        countries.add("Guiana");
        countries.add("Guiné");
        countries.add("Guiné Equatorial");
        countries.add("Guiné-Bissau");
        countries.add("Haiti");
        countries.add("Honduras");
        countries.add("Hungria");
        countries.add("Iémen");
        countries.add("Ilhas Marechal");
        countries.add("Índia");
        countries.add("Indonésia");
        countries.add("Irão");
        countries.add("Iraque");
        countries.add("Irlanda");
        countries.add("Islândia");
        countries.add("Israel");
        countries.add("Itália");
        countries.add("Jamaica");
        countries.add("Japão");
        countries.add("Jibuti");
        countries.add("Jordânia");
        countries.add("Laus");
        countries.add("Lesoto");
        countries.add("Letónia");
        countries.add("Líbia");
        countries.add("Listenstaine");
        countries.add("Lituânia");
        countries.add("Luxemburgo");
        countries.add("Macedónia");
        countries.add("Madagáscar");
        countries.add("MalásiaCuala ");
        countries.add("Maláui");
        countries.add("Maldivas");
        countries.add("Mali");
        countries.add("Malta");
        countries.add("Marrocos");
        countries.add("Maurícia");
        countries.add("Mauritânia");
        countries.add("México");
        countries.add("Mianmar");
        countries.add("Micronésia");
        countries.add("Moçambique");
        countries.add("Moldávia");
        countries.add("Mónaco");
        countries.add("Mongólia");
        countries.add("Montenegro");
        countries.add("Namíbia");
        countries.add("Nauru");
        countries.add("Nepal");
        countries.add("Nicarágua");
        countries.add("Níger");
        countries.add("Nigéria");
        countries.add("Noruega");
        countries.add("Nova Zelândia");
        countries.add("Omã");
        countries.add("Países Baixos");
        countries.add("Palau");
        countries.add("Panamá");
        countries.add("Papua Nova Guiné");
        countries.add("Paquistão");
        countries.add("Paraguai");
        countries.add("Peru");
        countries.add("Polónia");
        countries.add("Portugal");
        countries.add("Quénia");
        countries.add("Quirguistão");
        countries.add("Quiribáti");
        countries.add("Reino Unido");
        countries.add("República Centro-Africana");
        countries.add("República Checa");
        countries.add("República Democrática do Congo");
        countries.add("República Dominicana");
        countries.add("Roménia");
        countries.add("Ruanda");
        countries.add("Rússia");
        countries.add("Salomão");
        countries.add("Salvador ");
        countries.add("Samoa");
        countries.add("Santa Lúcia");
        countries.add("São Cristóvão e Neves");
        countries.add("São Marinho");
        countries.add("São Tomé e Príncipe");
        countries.add("São Vicente e Granadinas");
        countries.add("Seicheles");
        countries.add("Senegal");
        countries.add("Serra Leoa");
        countries.add("Sérvia");
        countries.add("Singapura");
        countries.add("Síria");
        countries.add("Somália");
        countries.add("Sri Lanca");
        countries.add("Suazilândia");
        countries.add("Sudão");
        countries.add("Sudão do Sul");
        countries.add("Suécia");
        countries.add("Suíça");
        countries.add("Suriname");
        countries.add("Tailândia");
        countries.add("Taiuã");
        countries.add("Tajiquistão");
        countries.add("Tanzânia");
        countries.add("Timor-Leste");
        countries.add("Togo");
        countries.add("Tonga");
        countries.add("Trindade e Tobago");
        countries.add("Tunísia");
        countries.add("Turcomenistão");
        countries.add("Turquia");
        countries.add("Tuvalu");
        countries.add("Ucrânia");
        countries.add("Uganda");
        countries.add("Uruguai");
        countries.add("Usbequistão");
        countries.add("VanuatuPorto ");
        countries.add("Vaticano");
        countries.add("Venezuela");
        countries.add("Vietname");
        countries.add("Zâmbia");
        countries.add("Zimbábue");
        return countries;
    }
}
